### ISSUE TITLE
Falsche Preisberechnung

### ISSUE THREAD

**Issue by neogeonow** [firegento/firegento-germansetup#169]
Hallo, 

dummerweise habe ich das Setup erneut ausgeführt mit folgendem Ergebnis:

In allen Nettopreisen die ich angelegt habe sind nun die 19% Steuern mit eingerechnet. Zudem kann ich bei der Index.Verwaltung "Artikel Preis" und "Altikel Flat Daten" nicht neu aufbauen, es erscheint folgende Meldung: "Indexer kann nicht gestartet werden."  

Ich wäre sehr dankbar für eine schnelle Hilfe!

**Comment by neogeonow** [comment]
Also das mit der Preisdarstellung habe ich hinbekommen! Bleibt noch die Index-Verwaltung. 
Ist dies überhaupt wichtig? 

Ich bin Laie, bitte daher um Idiotensichere Lösungsbeschreibungen :)

**Comment by mklooss** [comment]
es wird normalerweise im var/log verzeichnis eine exception log angelegt... da steht die Fehlermeldung drin.

**Comment by neogeonow** [comment]
Wie geschrieben bin ich nicht vom Fach, kannst du hieraus erkennen wie ich den o.g. Fehler beheben kann?

a:5:{i:0;s:215:"Error in file: "/homepages/30/d11844265/htdocs/store/app/code/core/Mage/Directory/data/directory_setup/data-install-1.6.0.0.php" - SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'AD' for key 1";i:1;s:935:"#0 /homepages/30/d11844265/htdocs/store/app/code/core/Mage/Core/Model/Resource/Setup.php(645): Mage::exception('Mage_Core', 'Error in file: ...')
#1 /homepages/30/d11844265/htdocs/store/app/code/core/Mage/Core/Model/Resource/Setup.php(391): Mage_Core_Model_Resource_Setup->_modifyResourceDb('data-install', '', '1.6.0.1')
#2 /homepages/30/d11844265/htdocs/store/app/code/core/Mage/Core/Model/Resource/Setup.php(289): Mage_Core_Model_Resource_Setup->_installData('1.6.0.1')
#3 /homepages/30/d11844265/htdocs/store/app/code/core/Mage/Core/Model/Resource/Setup.php(269): Mage_Core_Model_Resource_Setup->applyDataUpdates()
#4 /homepages/30/d11844265/htdocs/store/app/code/core/Mage/Core/Model/App.php(351): Mage_Core_Model_Resource_Setup::applyAllDataUpdates()
#5 /homepages/30/d11844265/htdocs/store/app/Mage.php(683): Mage_Core_Model_App->run(Array)
#6 /homepages/30/d11844265/htdocs/store/index.php(87): Mage::run('', 'store')
#7 {main}";s:3:"url";s:43:"/store/index.php/install/wizard/configPost/";s:11:"script_name";s:16:"/store/index.php";s:4:"skin";s:7:"default";}

**Comment by mklooss** [comment]
das ist kein Fehler von GermanSetup sondern in Magento direkt.

geht einfach in die Datenbank in die Tabelle "core_resource" und ändere die Version von "directory_setup" auf 1.6.0.1

``` SQL
UPDATE  `core_resource` SET  `version` =  '1.6.0.1', `data_version` =  '1.6.0.1' WHERE  `code` =  'directory_setup';
```

**Comment by neogeonow** [comment]
![bildschirmfoto 2013-06-19 um 10 46 18](https://f.cloud.github.com/assets/4697198/673586/c3950bd6-d8bc-11e2-91da-313d8cb98689.png)

"directory_setup" ist bereits auf Version  1.6.0.1, kann es an einer anderen Tabelle liegen?
