### ISSUE TITLE
Kundenbearbeitung im Backend nicht möflich

### ISSUE THREAD

**Issue by datenbrille** [firegento/firegento-germansetup#83]
```
Notice: Array to string conversion  in /home/karl/www/magento170.local/html/app/design/adminhtml/default/default/template/customer/tab/addresses.phtml on line 139

#0 /home/karl/www/magento170.local/html/app/design/adminhtml/default/default/template/customer/tab/addresses.phtml(139): mageCoreErrorHandler(8, 'Array to string...', '/home/karl/www/...', 139, Array)
#1 /home/karl/www/magento170.local/html/app/code/core/Mage/Core/Block/Template.php(241): include('/home/karl/www/...')
#2 /home/karl/www/magento170.local/html/app/code/core/Mage/Core/Block/Template.php(272): Mage_Core_Block_Template->fetchView('adminhtml/defau...')
#3 /home/karl/www/magento170.local/html/app/code/core/Mage/Core/Block/Template.php(286): Mage_Core_Block_Template->renderView()
#4 /home/karl/www/magento170.local/html/app/code/core/Mage/Adminhtml/Block/Template.php(81): Mage_Core_Block_Template->_toHtml()
#5 /home/karl/www/magento170.local/html/app/code/core/Mage/Core/Block/Abstract.php(863): Mage_Adminhtml_Block_Template->_toHtml()
#6 /home/karl/www/magento170.local/html/app/code/core/Mage/Adminhtml/Block/Customer/Edit/Tabs.php(64): Mage_Core_Block_Abstract->toHtml()
#7 /home/karl/www/magento170.local/html/app/code/core/Mage/Core/Block/Abstract.php(862): Mage_Adminhtml_Block_Customer_Edit_Tabs->_beforeToHtml()
#8 /home/karl/www/magento170.local/html/app/code/core/Mage/Core/Block/Text/List.php(43): Mage_Core_Block_Abstract->toHtml()
#9 /home/karl/www/magento170.local/html/app/code/core/Mage/Core/Block/Abstract.php(863): Mage_Core_Block_Text_List->_toHtml()
#10 /home/karl/www/magento170.local/html/app/code/core/Mage/Core/Block/Abstract.php(582): Mage_Core_Block_Abstract->toHtml()
#11 /home/karl/www/magento170.local/html/app/code/core/Mage/Core/Block/Abstract.php(526): Mage_Core_Block_Abstract->_getChildHtml('left', true)
#12 /home/karl/www/magento170.local/html/app/design/adminhtml/default/default/template/page.phtml(58): Mage_Core_Block_Abstract->getChildHtml('left')
#13 /home/karl/www/magento170.local/html/app/code/core/Mage/Core/Block/Template.php(241): include('/home/karl/www/...')
#14 /home/karl/www/magento170.local/html/app/code/core/Mage/Core/Block/Template.php(272): Mage_Core_Block_Template->fetchView('adminhtml/defau...')
#15 /home/karl/www/magento170.local/html/app/code/core/Mage/Core/Block/Template.php(286): Mage_Core_Block_Template->renderView()
#16 /home/karl/www/magento170.local/html/app/code/core/Mage/Adminhtml/Block/Template.php(81): Mage_Core_Block_Template->_toHtml()
#17 /home/karl/www/magento170.local/html/app/code/core/Mage/Core/Block/Abstract.php(863): Mage_Adminhtml_Block_Template->_toHtml()
#18 /home/karl/www/magento170.local/html/app/code/core/Mage/Core/Model/Layout.php(555): Mage_Core_Block_Abstract->toHtml()
#19 /home/karl/www/magento170.local/html/app/code/core/Mage/Core/Controller/Varien/Action.php(390): Mage_Core_Model_Layout->getOutput()
#20 /home/karl/www/magento170.local/html/app/code/core/Mage/Adminhtml/controllers/CustomerController.php(151): Mage_Core_Controller_Varien_Action->renderLayout()
#21 /home/karl/www/magento170.local/html/app/code/core/Mage/Core/Controller/Varien/Action.php(419): Mage_Adminhtml_CustomerController->editAction()
#22 /home/karl/www/magento170.local/html/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('edit')
#23 /home/karl/www/magento170.local/html/app/code/core/Mage/Core/Controller/Varien/Front.php(176): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#24 /home/karl/www/magento170.local/html/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#25 /home/karl/www/magento170.local/html/app/Mage.php(683): Mage_Core_Model_App->run(Array)
#26 /home/karl/www/magento170.local/html/index.php(87): Mage::run('', 'store')
#27 {main}
```

**Comment by therouv** [comment]
Das ist kein Fehler von GermanSetup, sondern ein Fehler von Magento. Der Fehler wird aber nur angezeigt, wenn man den Developer-Modus aktiviert hat.
